<a href="https://colab.research.google.com/github/Nethra07-star/PYTHON-FOR-ML/blob/main/240901065-assignment-3(b).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Question 3(B): Perform Matrix Manipulation on Stock Price Data
Problem Statement:
A stock analyst is analyzing two stocks using their daily price data recorded over a week.
Each stock's data is represented as a 5x3 matrix, where:
● Each row represents a day (5 days in total).
● Each column represents a different price feature: Open, High, and Low.
Write a Python program to:
● Compute the element-wise sum of the two matrices to analyze combined price
values.
● Compute the element-wise difference to understand the daily spread between the
two stocks.
Use NumPy for matrix operations.

In [3]:
import numpy as np
stock_a = np.array([
    [150.20, 155.00, 149.50],
    [154.50, 158.20, 153.10],
    [157.00, 159.00, 156.50],
    [158.10, 162.50, 157.80],
    [161.00, 165.00, 160.20]
])

stock_b = np.array([
    [145.00, 148.50, 144.20],
    [147.20, 150.00, 146.50],
    [149.50, 152.10, 148.80],
    [151.00, 155.30, 150.00],
    [153.50, 158.00, 152.90]
])


combined_prices = np.add(stock_a, stock_b)


price_spread = np.subtract(stock_a, stock_b)


print("--- Combined Stock Prices (Sum) ---")
print(combined_prices)

print("\n--- Daily Price Spread (Difference: A - B) ---")
print(price_spread)

--- Combined Stock Prices (Sum) ---
[[295.2 303.5 293.7]
 [301.7 308.2 299.6]
 [306.5 311.1 305.3]
 [309.1 317.8 307.8]
 [314.5 323.  313.1]]

--- Daily Price Spread (Difference: A - B) ---
[[5.2 6.5 5.3]
 [7.3 8.2 6.6]
 [7.5 6.9 7.7]
 [7.1 7.2 7.8]
 [7.5 7.  7.3]]
